version: '3'

vars:
  BAZEL: bazel
  PROTO_DIR: packages/proto/v1
  CMS_DIR: packages/cms
  DISCOVERY_DIR: packages/discovery

tasks:
  proto:build:
    desc: Build protobuf files with Bazel (generates Go code automatically)
    cmds:
      - '{{.BAZEL}} build //{{.PROTO_DIR}}:all'
    sources:
      - '{{.PROTO_DIR}}/*.proto'
      - '{{.PROTO_DIR}}/BUILD.bazel'

  proto:clean:
    desc: Clean generated proto files
    cmds:
      - '{{.BAZEL}} clean'

  cms:build:
    desc: Build CMS service
    cmds:
      - '{{.BAZEL}} build //{{.CMS_DIR}}/...'
    deps: [proto:build]

  cms:run:
    desc: Run CMS service
    cmds:
      - '{{.BAZEL}} run //{{.CMS_DIR}}/server:server'
    deps: [cms:build]

  discovery:build:
    desc: Build Discovery service (when implemented)
    cmds:
      - '{{.BAZEL}} build //{{.DISCOVERY_DIR}}/...'
    deps: [proto:build]

  discovery:run:
    desc: Run Discovery service
    cmds:
      - '{{.BAZEL}} run //{{.DISCOVERY_DIR}}/server:server'
    deps: [discovery:build]

  build:all:
    desc: Build entire project
    cmds:
      - '{{.BAZEL}} build //...'

  test:all:
    desc: Run all tests
    cmds:
      - '{{.BAZEL}} test //... --test_output=all'

  test:cms:
    desc: Run CMS service tests
    cmds:
      - '{{.BAZEL}} test //{{.CMS_DIR}}/... --test_output=all'

  test:cms:store:
    desc: Run CMS store tests
    cmds:
      - '{{.BAZEL}} test //{{.CMS_DIR}}/store:store_test --test_output=all'

  test:cms:service:
    desc: Run CMS service layer tests
    cmds:
      - '{{.BAZEL}} test //{{.CMS_DIR}}/v1:cms_test --test_output=all'

  test:discovery:
    desc: Run Discovery service tests
    cmds:
      - '{{.BAZEL}} test //{{.DISCOVERY_DIR}}/... --test_output=all'

  test:watch:
    desc: Run tests in watch mode (requires ibazel)
    cmds:
      - ibazel test //... --test_output=all

  status:
    desc: Show project status
    cmds:
      - echo "=== Mawjood Project Status ==="
      - echo "Proto files:"
      - ls -la {{.PROTO_DIR}}/*.proto
      - echo ""
      - echo "Bazel targets:"
      - '{{.BAZEL}} query //{{.PROTO_DIR}}:all'
      - echo ""
      - echo "Generated Go files (in bazel-bin):"
      - find bazel-bin/{{.PROTO_DIR}} -name "*.go" -type f 2>/dev/null || echo "Run 'task proto:build' to generate Go files"

  dev:setup:
    desc: Setup development environment
    cmds:
      - echo "Setting up Mawjood development environment..."
      - task build:all
      - echo "✅ Development environment ready!"

  default:
    desc: Show project status and available commands
    cmds:
      - task status
      - echo ""
      - echo "Available commands:"
      - echo "Build commands:"
      - echo "  task proto:build      - Build proto files and generate Go code"
      - echo "  task cms:build        - Build CMS service"
      - echo "  task discovery:build  - Build Discovery service"
      - echo "  task build:all        - Build entire project"
      - echo ""
      - echo "Run commands:"
      - echo "  task cms:run          - Run CMS service"
      - echo "  task discovery:run    - Run Discovery service"
      - echo ""
      - echo "Test commands:"
      - echo "  task test:all         - Run all tests"
      - echo "  task test:cms         - Run CMS service tests"
      - echo "  task test:cms:store   - Run CMS store tests"
      - echo "  task test:cms:service - Run CMS service layer tests"
      - echo "  task test:discovery   - Run Discovery service tests"
      - echo "  task test:watch       - Run tests in watch mode (requires ibazel)"
      - echo ""
      - echo "Setup commands:"
      - echo "  task dev:setup        - Setup development environment" 