version: '3'

vars:
  BAZEL: bazel
  PROTO_DIR: packages/proto/v1
  CMS_DIR: packages/cms
  DISCOVERY_DIR: packages/discovery

tasks:
  proto:build:
    desc: Build protobuf files with Bazel (generates Go code automatically)
    cmds:
      - '{{.BAZEL}} build //{{.PROTO_DIR}}:all'
    sources:
      - '{{.PROTO_DIR}}/*.proto'
      - '{{.PROTO_DIR}}/BUILD.bazel'

  proto:clean:
    desc: Clean generated proto files
    cmds:
      - '{{.BAZEL}} clean'

  cms:build:
    desc: Build CMS service
    cmds:
      - '{{.BAZEL}} build //{{.CMS_DIR}}/...'
    deps: [proto:build]

  cms:run:
    desc: Run CMS service
    cmds:
      - '{{.BAZEL}} run //{{.CMS_DIR}}/server:server'
    deps: [cms:build]

  discovery:build:
    desc: Build Discovery service (when implemented)
    cmds:
      - '{{.BAZEL}} build //{{.DISCOVERY_DIR}}/...'
    deps: [proto:build]

  discovery:run:
    desc: Run Discovery service
    cmds:
      - '{{.BAZEL}} run //{{.DISCOVERY_DIR}}/server:server'
    deps: [discovery:build]

  build:all:
    desc: Build entire project
    cmds:
      - '{{.BAZEL}} build //...'

  test:all:
    desc: Run all tests
    cmds:
      - '{{.BAZEL}} test //... --test_output=all'

  test:cms:
    desc: Run CMS service tests
    cmds:
      - '{{.BAZEL}} test //{{.CMS_DIR}}/... --test_output=all'

  test:cms:store:
    desc: Run CMS store tests
    cmds:
      - '{{.BAZEL}} test //{{.CMS_DIR}}/store:store_test --test_output=all'

  test:cms:service:
    desc: Run CMS service layer tests
    cmds:
      - '{{.BAZEL}} test //{{.CMS_DIR}}/v1:cms_test --test_output=all'

  test:discovery:
    desc: Run Discovery service tests
    cmds:
      - '{{.BAZEL}} test //{{.DISCOVERY_DIR}}/... --test_output=all'

  test:watch:
    desc: Run tests in watch mode (requires ibazel)
    cmds:
      - ibazel test //... --test_output=all

  status:
    desc: Show project status
    cmds:
      - echo "=== Mawjood Project Status ==="
      - echo "Proto files:"
      - ls -la {{.PROTO_DIR}}/*.proto
      - echo ""
      - echo "Bazel targets:"
      - '{{.BAZEL}} query //{{.PROTO_DIR}}:all'
      - echo ""
      - echo "Generated Go files (in bazel-bin):"
      - find bazel-bin/{{.PROTO_DIR}} -name "*.go" -type f 2>/dev/null || echo "Run 'task proto:build' to generate Go files"

  dev:setup:
    desc: Setup development environment
    cmds:
      - echo "Setting up Mawjood development environment..."
      - task build:all
      - echo "✅ Development environment ready!"

  run:
    desc: Start local development environment
    cmds:
      - 'echo "🎯 Starting Mawjood Local Development Environment..."'
      - 'echo ""'
      - 'echo "📦 Starting Docker services..."'
      - docker-compose up -d
      - 'echo ""'
      - 'echo "⏳ Waiting for services to be ready..."'
      - sleep 10
      - 'echo ""'
      - 'echo "🎉 Mawjood is now running locally!"'
      - 'echo ""'
      - 'echo "📍 Access your services:"'
      - 'echo "  📊 Database Admin:    http://localhost:8080"'
      - 'echo "  ⚙️  CMS gRPC UI:       http://localhost:8081"'
      - 'echo "  🔍 Discovery gRPC UI:  http://localhost:8082"'
      - 'echo ""'
      - 'echo "🔧 Useful commands:"'
      - 'echo "  task logs              - View all service logs"'
      - 'echo "  task stop              - Stop all services"'
      - 'echo "  task restart           - Restart services"'
      - 'echo "  task test              - Run tests"'
      - 'echo ""'
      - 'echo "Happy coding! 🚀"'

  stop:
    desc: Stop local development environment
    cmds:
      - 'echo "🛑 Stopping Mawjood services..."'
      - docker-compose down
      - 'echo "✅ All services stopped!"'

  restart:
    desc: Restart local development environment
    cmds:
      - 'echo "🔄 Restarting Mawjood services..."'
      - docker-compose restart
      - 'echo "✅ Services restarted!"'

  logs:
    desc: View logs from all services
    cmds:
      - docker-compose logs -f

  test:
    desc: Run all tests
    cmds:
      - 'echo "🧪 Running all tests..."'
      - go test ./packages/cms/...
      - go test ./packages/discovery/...
      - 'echo "✅ All tests completed!"'

  clean:
    desc: Clean up everything (removes data!)
    cmds:
      - 'echo "🧹 Cleaning up development environment..."'
      - 'echo "⚠️  This will remove all database data!"'
      - docker-compose down -v
      - docker system prune -f
      - 'echo "✅ Cleanup complete!"'

  default:
    desc: Show help and available commands
    cmds:
      - 'echo "🎯 Mawjood - Content Discovery Platform"'
      - 'echo ""'
      - 'echo "🚀 Quick Start:"'
      - 'echo "  task run               - Start local development environment"'
      - 'echo ""'
      - 'echo "📋 Common Commands:"'
      - 'echo "  task logs              - View service logs"'
      - 'echo "  task test              - Run tests"'
      - 'echo "  task restart           - Restart services"'
      - 'echo "  task stop              - Stop services"'
      - 'echo ""'
      - 'echo "🔧 Development Commands:"'
      - 'echo "  task proto:build       - Build protobuf files"'
      - 'echo "  task build:all         - Build entire project"'
      - 'echo "  task clean             - Clean up (removes data!)"'
      - 'echo ""'
      - 'echo "💡 Need help? Check README.md for full documentation"' 