version: '3'

vars:
  BAZEL: bazel
  PROTO_DIR: packages/proto/v1
  CMS_DIR: packages/cms
  DISCOVERY_DIR: packages/discovery

tasks:
  proto:build:
    desc: Build protobuf files with Bazel (generates Go code automatically)
    cmds:
      - '{{.BAZEL}} build //{{.PROTO_DIR}}:all'
    sources:
      - '{{.PROTO_DIR}}/*.proto'
      - '{{.PROTO_DIR}}/BUILD.bazel'

  proto:clean:
    desc: Clean generated proto files
    cmds:
      - '{{.BAZEL}} clean'

  cms:build:
    desc: Build CMS service
    cmds:
      - '{{.BAZEL}} build //{{.CMS_DIR}}/...'
    deps: [proto:build]

  cms:run:
    desc: Run CMS service
    cmds:
      - '{{.BAZEL}} run //{{.CMS_DIR}}/server:server'
    deps: [cms:build]

  discovery:build:
    desc: Build Discovery service (when implemented)
    cmds:
      - '{{.BAZEL}} build //{{.DISCOVERY_DIR}}/...'
    deps: [proto:build]

  build:all:
    desc: Build entire project
    cmds:
      - '{{.BAZEL}} build //...'

  test:all:
    desc: Run all tests
    cmds:
      - '{{.BAZEL}} test //...'

  status:
    desc: Show project status
    cmds:
      - echo "=== Mawjood Project Status ==="
      - echo "Proto files:"
      - ls -la {{.PROTO_DIR}}/*.proto
      - echo ""
      - echo "Bazel targets:"
      - '{{.BAZEL}} query //{{.PROTO_DIR}}:all'
      - echo ""
      - echo "Generated Go files (in bazel-bin):"
      - find bazel-bin/{{.PROTO_DIR}} -name "*.go" -type f 2>/dev/null || echo "Run 'task proto:build' to generate Go files"

  dev:setup:
    desc: Setup development environment
    cmds:
      - echo "Setting up Mawjood development environment..."
      - task build:all
      - echo "✅ Development environment ready!"

  default:
    desc: Show project status and available commands
    cmds:
      - task status
      - echo ""
      - echo "Available commands:"
      - echo "  task proto:build    - Build proto files and generate Go code"
      - echo "  task cms:build      - Build CMS service"
      - echo "  task cms:run        - Run CMS service"
      - echo "  task build:all      - Build entire project"
      - echo "  task test:all       - Run all tests"
      - echo "  task dev:setup      - Setup development environment" 